// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hamiltonFilter
Rcpp::List hamiltonFilter(int bigt, int m, int p, int h, Eigen::Map<Eigen::MatrixXd> e, Eigen::Map<Eigen::MatrixXd> sig2, Eigen::Map<Eigen::MatrixXd> Qhat);
RcppExport SEXP _msvar_hamiltonFilter(SEXP bigtSEXP, SEXP mSEXP, SEXP pSEXP, SEXP hSEXP, SEXP eSEXP, SEXP sig2SEXP, SEXP QhatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type bigt(bigtSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type e(eSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type Qhat(QhatSEXP);
    rcpp_result_gen = Rcpp::wrap(hamiltonFilter(bigt, m, p, h, e, sig2, Qhat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_msvar_hamiltonFilter", (DL_FUNC) &_msvar_hamiltonFilter, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_msvar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
