# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hamilton filter
#'
#' @export
hamiltonFilter <- function(bigt, m, p, h, e, sig2, Qhat) {
    .Call(`_msvar_hamiltonFilter`, bigt, m, p, h, e, sig2, Qhat)
}

