# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hamilton filter
#'
#' @export
hamiltonFilter <- function(bigt, m, p, h, e, sig2, Qhat) {
    .Call(`_msvar_hamiltonFilter`, bigt, m, p, h, e, sig2, Qhat)
}

#' predict_internal
#'
predict_cpp <- function(samples, Q, Bk, sigmaU, fp_last, h, m, p, Z_init) {
    .Call(`_msvar_predict_cpp`, samples, Q, Bk, sigmaU, fp_last, h, m, p, Z_init)
}

